networks:
  autenticacion:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.6.0/24" 
    external: false

volumes:
  postgres-db:
    external: false

services:
  usuarios:
    image: postgres:alpine
    container_name: usuarios
    restart: unless-stopped
    #significa que si se reinicia el contenedor, se reinicia el servicio automaticamente
    env_file:
      - .env.db
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 2s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
      #- ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf #indicamos que como archivo de configuracion usemos uno que nosotros configuremos
      #- /postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./initdb:/docker-entrypoint-initdb.d #apenas inicie que tome estos valores
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - 5436:5432
    networks:
      autenticacion:
        ipv4_address: 172.24.6.10